#
# Managed CI Workflow - PRE TEST
# DO NOT remove this file.  Doing so will break the entire managed CI workflow.
# NOTE that customizing this file is optional and it will work as-is.

name: CI PRE TEST
on:
  workflow_call:

jobs:
  pre-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.3.0

      # first restore, the variables artifact does not exist, so we load from the checked out repo
      - uses: glcp/mci-actions-variables-restore@v2
        with:
          use-artifact: false

#
# Add project-specific pre-test steps here
#

      - uses: glcp/mci-actions-variables-backup@v2
        with:
          artifact-name: variables-test

      - uses: glcp/mci-actions-workspace-backup@v1
        if: env.UNIT_TEST_WORKSPACE_BACKUP == 'true'
        with:
          artifact-name: workspace-test
          zip-name: workspace-test.zip
